### PR TITLE
Specify packaging version

### PR DESCRIPTION
**Pull request by wellshs**
https://github.com/nexB/pip-requirements-parser/issues/10

### CODE REVIEW

**Comment by wellshs** [comment]
@pombredanne Hi!, can you review this one?

**Comment by pombredanne** [comment]
@wellshs Thanks.... I think we need a bit more than this. In particular we would need to either:
- update the setup.cfg to put a temporary cap on the packaging version
- alternatively vendoring packaging would be best short term

Your proposed requirements.update only work if using a checkout and running configure, and will not fix a pip install pip-audit

**Comment by pombredanne** [comment]
I am closing in this in favor of https://github.com/nexB/pip-requirements-parser/pull/3
Thank you ++ for reporting the issue and helping fixing this.

**Comment by wellshs** [comment]
Oh, thanks for kind explanation and fixing this issue!
I will check out patch work to me!

**Pull request closed without merging**
