### PR TITLE
packvers-imports-instead-of-packaging

### PR DESCRIPTION
**Pull request by swastkk**
Resolving - [Import Errors in python-inspector requirments module](https://github.com/nexB/python-inspector/pull/109)
Signed-off-by: swastik <swastkk@gmail.com>

### CODE REVIEW

**Comment by swastkk** [comment]
@pombredanne please have a look :")

**Comment by swastkk** [comment]
Need a help, don't able to understand why getting `pytest` not getting imported in some of the test files like `tests/test_requirements_parser.py`, any specific reason behind it ? because it is the only reason behind these failing tests :")

**Comment by pombredanne** [comment]
@swastkk Thanks... but I am not sure I get the benefits?
packvers is a fork of packaging, but here I have already vendored a subset of packaging that deals with LegacyVersion. I am not sure there is a need to further rename this and remove the usage of the standard packaging otherwise.

**Comment by swastkk** [comment]
> @swastkk Thanks... but I am not sure I get the benefits? packvers is a fork of packaging, but here I have already vendored a subset of packaging that deals with LegacyVersion. I am not sure there is a need to further rename this and remove the usage of the standard packaging otherwise.

Actually I want to know why I am getting issues in python-inspector, since it used the package `pip-requirments-parse` , tests are also failing in that :")

**Pull request closed without merging**
